export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT = "LOGOUT";

export const REFRESH_TOKEN_REQUEST = 'REFRESH_TOKEN_REQUEST';
export const REFRESH_TOKEN_SUCCESS = 'REFRESH_TOKEN_SUCCESST';
export const REFRESH_TOKEN_FAILURE = 'REFRESH_TOKEN_FAILURE';

export const UPDATE_USER_REQUEST = 'UPDATE_USER_REQUEST';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const UPDATE_USER_FAILURE = 'UPDATE_USER_FAILURE';

export const FETCH_USER_REQUEST = 'FETCH_USER_REQUEST';
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS';
export const FETCH_USER_FAILURE = 'FETCH_USER_FAILURE';

export const FETCH_WEATHER_REQUEST = 'FETCH_WEATHER_REQUEST';
export const FETCH_WEATHER_SUCCESS = 'FETCH_WEATHER_SUCCESS';
export const FETCH_WEATHER_FAILURE = 'FETCH_WEATHER_FAILURE';

export const FORECAST_WEATHER_REQUEST = 'FORECAST_WEATHER_REQUEST';
export const FORECAST_WEATHER_SUCCESS = 'FORECAST_WEATHER_SUCCESS';
export const FORECAST_WEATHER_FAILURE = 'FORECAST_WEATHER_FAILURE';

export const CURRENT_WEATHER_REQUEST = 'FORECAST_WEATHER_REQUEST';
export const CURRENT_WEATHER_SUCCESS = 'FORECAST_WEATHER_SUCCESS';
export const CURRENT_WEATHER_FAILURE = 'FORECAST_WEATHER_FAILURE';